build:
  command: bash ./netlify-build.sh
  publish: dist
  environment:
    NODE_VERSION: 18.18.0
    NPM_VERSION: 9.8.1

redirects:
  - from: /*
    to: /index.html
    status: 200

headers:
  - for: /*
    values:
      Cache-Control: public, max-age=0, must-revalidate
      X-Frame-Options: DENY
      X-XSS-Protection: 1; mode=block
      X-Content-Type-Options: nosniff
      Referrer-Policy: strict-origin-when-cross-origin 