[build]
  command = "node netlify-build.js"
  publish = "dist"

# Handle SPA routing by redirecting all requests to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Set custom headers for caching and security
[[headers]]
  for = "/*"
    [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/index.html"
    [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# Environment variables
[build.environment]
  CI = "false"  # Prevent builds from failing on warnings
  NODE_VERSION = "18" # Ensure compatible Node version
  NPM_FLAGS = "--legacy-peer-deps --no-audit --no-fund"
  VITE_CJS_IGNORE_WARNING = "true"

# Optimize build settings
[build.processing]
  skip_processing = false

# Handle common build failures
[build.lifecycle]
  onBuild = "echo 'Running custom build script...'"
  onError = "echo 'Error detected, checking logs...'" 